name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [ '23' ]
        maven: [ '3.9.6' ]
        os: [ 'ubuntu-22.04' ]
    name: Build (Java ${{ matrix.java }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Set up Maven ${{ matrix.maven }}
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: ${{ matrix.maven }}

      - name: Build the JAR
        run: mvn clean package -B -U

      - name: Verify JAR creation
        run: ls -al target

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: "Release v${{ github.run_number }}"
          body: "Automated release for build #${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/streamspace-0.0.1.jar  # Update the JAR name as needed
          asset_name: streamspace-${{ github.run_number }}.jar
          asset_content_type: application/java-archive
          
